### ISSUE TITLE
In bisulfite mode, run Bismark using local alignments 

### ISSUE THREAD

**Issue by FelixKrueger** [StevenWingett/FastQ-Screen#11]
To avoid having to run FastQ Screen on trimmed FastQ files in `--bisulfite` mode, could you please allow Bismark to be run using local alignments (flag: `--local`), similar to what you are doing already for Bowtie2 and BWA?

**Comment by StevenWingett** [comment]
We looked at the effect of making the Bismark option --local the default by processing the Bismark Test Dataset (results attached).  This resulted in a large number of extra reads now categorised as multi-mapping.  This was considered excessive.  Consequently, instead of making --local the Bismark default, FastQ Screen now has a new --bismark option to which Bismark parameters may be passed (for example --bismark "--local"  maps with Bismark in local mode.

Commit: aaac84af005ebc79bcde966956d40cd1e2c9ca8d

[Mapping_Results_Bismark.zip](https://github.com/StevenWingett/FastQ-Screen/files/4702907/Mapping_Results_Bismark.zip)
